"""
extra/gen_stats.py — what the generations look like, from saved per-example outputs (no GPU, no model).

For every BOOKS run (or the --models given) and each generation metric (VerbMem sampled + greedy, KnowMem-forget,
KnowMem-retain): the fraction of responses that are empty / whitespace-only, the fraction with no letter or digit at
all (whitespace + punctuation only, e.g. ',,  , ,,,'), the mean share of characters that are letters/digits, the mean
length in characters and in words (maximal runs of letters/digits), and the metric's mean ROUGE-L x100.

    .venvs/paper/bin/python -m extra.gen_stats --results dl_acc1/results dl_acc2/results dl_acc3/results \
        --out tables/generation_stats
    .venvs/paper/bin/python -m extra.gen_stats ... --samples books/ga_gdr_s42/bnb4 --n 5   # print generations
"""

import argparse
import csv
import json
import re
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE))

from compare_results import LABEL, load_all  # noqa: E402

FILES = [("VerbMem sampled", "verbmem_sample.json"), ("VerbMem greedy", "verbmem_greedy.json"),
         ("KnowMem forget", "knowmem_f.json"), ("KnowMem retain", "knowmem_r.json")]
WORD = re.compile(r"[A-Za-z0-9]+")


def stats(per_example):
    resp = [r["response"] for r in per_example]
    n = len(resp)
    alnum = [sum(ch.isalnum() for ch in s) / len(s) if s else 0.0 for s in resp]
    return {
        "n": n,
        "empty_or_ws": sum(not s.strip() for s in resp) / n,
        "no_alnum": sum(not WORD.search(s) for s in resp) / n,
        "alnum_char_share": statistics.fmean(alnum),
        "mean_chars": statistics.fmean(len(s) for s in resp),
        "mean_words": statistics.fmean(len(WORD.findall(s)) for s in resp),
        "rougeL_x100": 100 * statistics.fmean(r["rougeL"] for r in per_example),
    }


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", nargs="+", default=["dl_acc1/results", "dl_acc2/results", "dl_acc3/results"])
    ap.add_argument("--corpus", default="books")
    ap.add_argument("--out", default="tables/generation_stats", help="writes <out>.md and <out>.csv")
    ap.add_argument("--samples", nargs="*", default=[], help="corpus/model/tag runs to print generations of")
    ap.add_argument("--n", type=int, default=5, help="generations per metric for --samples")
    a = ap.parse_args(argv)
    runs = load_all([Path(r) for r in a.results])

    if a.samples:
        for spec in a.samples:
            d = runs[tuple(spec.split("/"))]
            for name, f in FILES:
                if f == "verbmem_greedy.json" or f == "knowmem_f.json" or not (d / f).exists():
                    continue
                print(f"=== {spec} — {name} (first {a.n} examples by idx) ===")
                for r in sorted(json.loads((d / f).read_text())["per_example"], key=lambda r: r["idx"])[:a.n]:
                    q = r.get("question", r["prompt"][-120:])
                    print(f"[idx {r['idx']}] {'Q' if 'question' in r else 'prompt end'}: {q!r}")
                    print(f"  gt: {r['gt'][:160]!r}")
                    print(f"  response: {r['response'][:240]!r}   (ROUGE-L {r['rougeL']:.3f})")
                print()
        return

    header = ["Method", "Model", "Tag", "Metric", "n", "empty/whitespace %", "no letter or digit %",
              "letters+digits share of chars %", "mean chars", "mean words", "ROUGE-L x100"]
    rows = []
    for (corpus, model, tag), d in sorted(runs.items()):
        if corpus != a.corpus or tag.startswith("fp32diag"):
            continue
        meth = model if model in ("target", "retrain") else model.rpartition("_s")[0]
        for name, f in FILES:
            if not (d / f).exists():
                continue
            s = stats(json.loads((d / f).read_text())["per_example"])
            rows.append([LABEL.get(meth, meth), model, tag, name, s["n"], f"{100 * s['empty_or_ws']:.0f}",
                         f"{100 * s['no_alnum']:.0f}", f"{100 * s['alnum_char_share']:.0f}", f"{s['mean_chars']:.0f}",
                         f"{s['mean_words']:.1f}", f"{s['rougeL_x100']:.1f}"])
    out = Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out.with_suffix(".csv"), "w", newline="") as fh:
        csv.writer(fh).writerows([header] + rows)
    md = [f"# Generation statistics ({a.corpus}) — generated by extra/gen_stats.py from saved per-example outputs\n",
          "'no letter or digit' = the response contains only whitespace and punctuation (e.g. ',,  , ,,,'); "
          "'words' = maximal runs of ASCII letters/digits. Responses are what the authors' generation code returned "
          "(VerbMem: max 128 new tokens; KnowMem: max 32, cut at '\\n\\n' / 'Question').\n",
          "| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    md += ["| " + " | ".join(map(str, r)) + " |" for r in rows]
    out.with_suffix(".md").write_text("\n".join(md) + "\n")
    print(f"wrote {out.with_suffix('.md')} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
